#GrepIU Config YAML
grepiu:
  file:
    path: "C:/data/fileupload/"
  oauth:
    login:
      url: "http://localhost:8010"
    token:
      url: "http://localhost:8010/oauth/token"

management:
  health:
    db:
      enabled: false

server:
  port: 8010

spring:
  profiles: local
  aop:
    proxy-target-class: true
  application:
    admin:
      enabled: false
  data:
    mongodb:
      database: grepiu
      host: "0.0.0.0"
      username: test
      password: test
      port: 0
      repositories:
       type: auto
    redis:
       host: "0.0.0.0"
       port: 0
  servlet:
    multipart:
      enabled: true
      max-file-size: 128KB
      max-request-size: 128KB

logging:
  level:
    org.springframework.web: DEBUG

---

grepiu:
  file:
    path: "/home/server/data/"
  oauth:
    login:
      url: "https://www.grepiu.com/login"
    token:
      url: "https://conf.grepiu.com/oauth/token"

management:
  health:
    db:
      enabled: false

server:
  port: 8080

spring:
  profiles: prod
  aop:
    proxy-target-class: true
  application:
    admin:
      enabled: false
  data:
    mongodb:
      database: grepiu
      host: "0.0.0.0"
      username: unknow
      password: unknow
      port: 0
      repositories:
       type: auto
    redis:
       host: "0.0.0.0"
       port: 0
  servlet:
    multipart:
      enabled: true
      max-file-size: 128KB
      max-request-size: 128KB

logging:
  level:
    org.springframework.web: INFO
  file: "/home/server/log/app.log"